name: test:add-function
on: push
jobs:
  gitHubActionForPytest:
    name: Add Function Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test Add Function
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: python setup.py develop && pytest __tests__/test_add.py -vs
